version: "3.9"

services:
  web:
    container_name: vk-images-web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./config/.env
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
