# Generated by Django 3.2.9 on 2021-11-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='proportions',
            field=models.FloatField(default=0, editable=False, verbose_name='Пропорции'),
            preserve_default=False,
        ),
    ]
