# Generated by Django 3.2.9 on 2021-11-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(editable=False, upload_to='image', verbose_name='Изображение'),
        ),
    ]
